package com.acroninspector.app.presentation.fragment.notifications.unreaded

import com.acroninspector.app.presentation.fragment.notifications.NotificationsView

interface NewNotificationsView: NotificationsView